---
- name: Configure nodes with Non Free firmware Repositories
  become: true
  hosts: cluster
  tasks:
    - name: Add non-free to sources.list
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: "^(deb|deb-src)(.*)(?<!non-free)$"
        replace: '\1\2 non-free'

    - name: Run apt update
      ansible.builtin.apt:
        update_cache: true

    - name: Run apt upgrade
      ansible.builtin.apt:
        upgrade: safe

- name: Install non-free wifi firmware
  hosts: cluster
  become: true
  vars:
    regdom: "CA"
  tasks:
    - name: Install firmware-iwlwifi
      ansible.builtin.apt:
        name:
          - firmware-iwlwifi
          - firmware-realtek
          - wpasupplicant
          - wireless-tools
          - iproute2
          - crda
          - iw
        state: present

    - name: Set regulatory Domain
      command: "iw reg set {{ regdom }}"

    - name: Configure CRDA
      copy:
        content: |
          "options cfg80211 ieee80211_regdom={{ regdom }}"
        dest: /etc/modprobe.d/cfg80211.conf
        owner: root
        group: root
        mode: "0644"

    - name: Reload iwlwifi module
      block:
        - name: Remove iwlwifi module
          ansible.builtin.command:
            cmd: modprobe -r iwlwifi
          changed_when: false
          failed_when: false

        - name: Load iwlwifi module
          ansible.builtin.command:
            cmd: modprobe iwlwifi
          changed_when: false
          failed_when: false

    - name: Reload realtek module
      block:
        - name: Remove realtek module
          ansible.builtin.command:
            cmd: modprobe -r realtek
          changed_when: false
          failed_when: false

        - name: Load realtek module
          ansible.builtin.command:
            cmd: modprobe realtek
          changed_when: false
          failed_when: false
