---
- name: Configure nodes with authorized key
  hosts: cluster
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        exclusive: true
        key: "{{ lookup('file', ansible_ssh_public_key_file) }}"
