---
- name: Prepare Ceph for MariaDB
  hosts: cluster
  become: true
  tasks:
    - name: Check if the RBD image for MariaDB already exists
      ansible.builtin.command:
        cmd: "rbd --id sql --pool sql ls"
      register: rbd_image_list
      changed_when: false

    # yamllint disable rule:line-length
    - name: Create a thin-provisioned RBD image for MariaDB
      ansible.builtin.command:
        cmd: "rbd --id sql --pool sql create mariadb-disk --size 1024000 --image-feature layering,exclusive-lock,object-map,fast-diff,deep-flatten"
      when: "inventory_hostname == groups['cluster'][0] and 'mariadb-disk' not in rbd_image_list.stdout"
      register: rbd_image_create
      changed_when: "'pool' in rbd_image_create.stdout"

    - name: Verify sql Block Device
      ansible.builtin.command:
        cmd: "rbd ls --id sql --pool sql"
      register: verify_maria_db_block_device
      failed_when: "'mariadb-disk' not in verify_maria_db_block_device.stdout"
      changed_when: false

    - name: Verify mariadb-disk
      ansible.builtin.command:
        cmd: "rbd info mariadb-disk --id sql --pool sql"
      register: verify_maria_mariadb_disk
      failed_when: "'mariadb-disk' not in verify_maria_mariadb_disk.stdout"
      changed_when: false

    - name: Check if mariadb-disk rbd device is already mapped
      ansible.builtin.command:
        cmd: "rbd showmapped --id sql"
      register: rbd_showmapped
      changed_when: false

    - name: Map mariadb-disk rbd device to host
      ansible.builtin.command:
        cmd: "rbd map mariadb-disk --id sql --pool sql"
      register: map_mariadb_disk
      failed_when: "'/dev/rbd0' not in map_mariadb_disk.stdout"
      changed_when: "'/dev/rbd0' in map_mariadb_disk.stdout"
      when: "'mariadb-disk' not in rbd_showmapped.stdout"

    - name: Add nofail and noatime options for /dev/rbd0 in /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/dev/rbd0'
        line: '/dev/rbd0 /var/lib/mysql xfs nofail,noauto,noatime 0 0'
        state: present

    - name: RdbMap Configuration
      ansible.builtin.copy:
        src: rbdmap
        dest: /etc/ceph/rbdmap
        owner: root
        group: root
        mode: "0700"

    - name: Enable RdbMap
      ansible.builtin.service:
        name: rbdmap
        state: restarted
        enabled: true

- name: Format the MariaDB RDB device
  hosts: cluster[0]
  become: true
  tasks:
    - name: Check if XFS filesystem exists on /dev/rbd0
      ansible.builtin.command:
        cmd: "blkid -s TYPE -o value /dev/rbd0"
      register: check_xfs_filesystem
      failed_when: false
      changed_when: false

    - name: Create XFS filesystem on /dev/rbd0
      community.general.filesystem:
        dev: /dev/rbd0
        fstype: xfs
      when: check_xfs_filesystem.stdout != 'xfs'

- name: Install MariaDB on Nodes
  hosts: cluster
  become: true
  tasks:

    - name: Install MariaDB packages
      ansible.builtin.apt:
        name:
          - mariadb-server
          - mariadb-client
          - mariadb-backup
          - python3-pymysql
        state: present
- name: Mount RBD image on all nodes
  hosts: cluster
  become: true
  tasks:

    - name: Mount /dev/rbd0 to /var/lib/mysql
      ansible.posix.mount:
        path: /var/lib/mysql
        src: /dev/rbd0
        fstype: xfs
        state: mounted
        boot: true

    - name: Ensure /var/lib/mysql directory exists and has correct permissions
      ansible.builtin.file:
        path: /var/lib/mysql
        state: directory
        owner: mysql
        group: mysql
        mode: '0700'

    - name: List contents of /var/lib/mysql
      ansible.builtin.command:
        cmd: "ls -l /var/lib/mysql"
      register: list_mysql_contents
      changed_when: false

    - name: Display contents of /var/lib/mysql
      ansible.builtin.debug:
        var: list_mysql_contents.stdout_lines

    - name: Check disk usage of /var/lib/mysql
      ansible.builtin.command:
        cmd: "df -h /var/lib/mysql"
      register: disk_usage
      changed_when: false

    - name: Display disk usage of /var/lib/mysql
      ansible.builtin.debug:
        var: disk_usage.stdout_lines


- name: Populate MariaDB on Ceph
  hosts: cluster[0]
  become: true
  tasks:
    - name: Populate /var/lib/mysql
      ansible.builtin.command:
        cmd: mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
      changed_when: false

- name: Init MariaDB
  hosts: cluster
  become: true
  tasks:
    - name: Stop MariaDB service
      ansible.builtin.systemd:
        name: mariadb
        state: stopped

    - name: Copy MariaDB configuration file
      ansible.builtin.copy:
        src: my.cnf
        dest: /etc/my.cnf
        owner: root
        group: root
        mode: "0600"

    - name: Start MariaDB service
      ansible.builtin.systemd:
        name: mariadb
        state: restarted
        enabled: true
      environment:
        MYSQLD_OPTS: "--defaults-extra-file=/etc/mysql/conf.d/custom_my.cnf"
