---
- name: Install OpenStack
  hosts: cluster
  become: true
  tasks:
    - name: Add OpenStack repository key
      ansible.builtin.apt_key:
        url: "https://download.ceph.com/keys/release.asc"
        state: present

    - name: Add OpenStack repository
      ansible.builtin.apt_repository:
        repo: "deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-backports main"
        state: present
        filename: openstack

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install OpenStack packages
      ansible.builtin.apt:
        name:
          - python3-openstackclient
          - keystone
          - glance
          - cinder-api
          - cinder-scheduler
          - cinder-volume
          - nova-api
          - nova-conductor
          - nova-scheduler
          - nova-compute
          - neutron-server
          - neutron-plugin-ml2
          - neutron-openvswitch-agent
        state: present
- name: Generate rbd_secret_uuid
  hosts: cluster
  become: true
  tasks:
    - name: Generate a new UUID for rbd_secret_uuid
      ansible.builtin.command:
        cmd: uuidgen
      register: rbd_secret_uuid_result
      changed_when: false
      when: "inventory_hostname == groups['cluster'][0]"

    - name: Set rbd_secret_uuid fact
      ansible.builtin.set_fact:
        rbd_secret_uuid: "{{ rbd_secret_uuid_result.stdout }}"
      when: "inventory_hostname == groups['cluster'][0]"

    - name: Share rbd_secret_uuid with other hosts in the cluster
      ansible.builtin.set_fact:
        rbd_secret_uuid: "{{ hostvars[groups['cluster'][0]]['rbd_secret_uuid'] }}"
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: "inventory_hostname == groups['cluster'][0]"
      loop: "{{ groups['cluster'][1:] }}"

- name: Configure OpenStack services to use Ceph
  hosts: cluster
  become: true
  tasks:
    - name: Configure Glance to use Ceph
      ansible.builtin.blockinfile:
        path: /etc/glance/glance-api.conf
        block: |
          [glance_store]
          stores = rbd
          rbd_store_pool = glance
          rbd_store_user = glance
          rbd_store_ceph_conf = /etc/ceph/ceph.conf
          rbd_store_chunk_size = 8
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Configure Cinder to use Ceph
      ansible.builtin.blockinfile:
        path: /etc/cinder/cinder.conf
        block: |
          [DEFAULT]
          enabled_backends = rbd

          [rbd]
          volume_driver = cinder.volume.drivers.rbd.RBDDriver
          rbd_pool = cinder
          rbd_user = cinder
          rbd_secret_uuid = {{ rbd_secret_uuid }}
          rbd_ceph_conf = /etc/ceph/ceph.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Configure Nova to use Ceph
      ansible.builtin.blockinfile:
        path: /etc/nova/nova.conf
        block: |
          [libvirt]
          images_type = rbd
          images_rbd_pool = nova
          images_rbd_ceph_conf = /etc/ceph/ceph.conf
          rbd_user = nova
          rbd_secret_uuid = {{ rbd_secret_uuid }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Restart OpenStack services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: true
      loop:
        - glance-api
        - cinder-api
        - cinder-scheduler
        - cinder-volume
        - nova-api
        - nova-conductor
        - nova-scheduler
        - nova-compute
        - neutron-server
        - neutron-openvswitch-agent
