---
- name: Reboot cluster
  hosts: cluster
  become: true
  tasks:
    - name: Gather Ceph FSID
      ansible.builtin.shell:
        cmd: cephadm shell -- ceph fsid 2>/dev/null
      args:
        executable: /bin/bash
      register: ceph_fsid
      changed_when: ceph_fsid.rc != 0

    - name: "Set fact: Ceph FSID"
      ansible.builtin.set_fact:
        ceph_fsid_name: "{{ ceph_fsid.stdout }}"

    - name: Gather Ceph Logical Volume Name
      ansible.builtin.shell: set -o pipefail |
        pvdisplay -C --select pv_name={{ ceph_disk }} -o lv_name --noheadings | xargs
      args:
        executable: /bin/bash
      register: ceph_lv_name
      changed_when: ceph_lv_name.rc != 0

    - name: "Set Fact: Ceph Logical Volume name"
      no_log: true
      ansible.builtin.set_fact:
        ceph_lv: "{{ ceph_lv_name.stdout }}"

    - name: Remove Ceph Cluster by FSID
      ansible.builtin.shell: set -o pipefail |
        cephadm rm-cluster --fsid {{ ceph_fsid_name }} --force
      args:
        executable: /bin/bash
      register: ceph_fsid_rm
      changed_when: ceph_fsid_rm.rc != 0

    - name: Gather Ceph Volume Group Name
      ansible.builtin.shell: set -o pipefail |
        pvdisplay -C --select pv_name={{ ceph_disk }} -o vg_name --noheadings | xargs
      args:
        executable: /bin/bash
      register: ceph_vg_name
      changed_when: ceph_vg_name.rc != 0

    - name: "Set Fact: Ceph Volume Group name"
      no_log: true
      ansible.builtin.set_fact:
        ceph_vg: "{{ ceph_vg_name.stdout }}"

    - name: Delete Logical Volumes
      ansible.builtin.command:
        cmd: "lvremove --yes /dev/{{ ceph_vg }}/{{ ceph_lv }} --force --force"
      register: lvremove
      changed_when: lvremove.rc != 0

    - name: Delete Volume Groups
      ansible.builtin.command:
        cmd: "vgremove --yes {{ ceph_vg }} --force --force"
      register: vgremove
      changed_when: vgremove.rc != 0

    - name: Delete Physical Volumes
      ansible.builtin.command:
        cmd: "pvremove --yes {{ ceph_disk }} --force --force"
      register: pvremove
      changed_when: pvremove.rc != 0

    - name: Remove Ceph data directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/ceph/ceph.conf
        - /etc/ceph/ceph.client.admin.keyring
        - /var/lib/ceph
        - /etc/ceph

    - name: Reboot
      ansible.builtin.reboot:
        reboot_command: "systemctl reboot"
